apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-sync-prune-policies
spec:
  destination:
    namespace: stage
    server: https://kubernetes.default.svc
  project: default
  source:
  # It's possible to override helm values through different ways such as "valueFiles", "values", "valuesObject" and "parameters". 
  # Values injections have the following order of precedence parameters > valuesObject > values > valueFiles > helm repository values.yaml Or rather
    helm:
      releaseName: saba-application-from-policies
      valueFiles:
        - custom-values.yaml
    path: v03-argocd-applications/application-helm-policies/nginx
    #    repoURL: https://github.com/devopshobbies/argocd-tutorial.git
    repoURL: https://github.com/saeed-didar/argocd-tutorial.git
    targetRevision: main
#################################################### sync policies and options #################################   
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - FailOnSharedResource=true
    - PruneLast=true
    - ApplyOutOfSyncOnly=true
    - Replace=true
    managedNamespaceMetadata:
      labels: # The labels to set on the application namespace
        any: SabaApp1
        you: like1
      annotations: # The annotations to set on the application namespace
        the: SabaApp2
        applies: like2
        annotations: on-the-namespace-stage
    automated:
      prune: true
      selfHeal: true

