apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-from-external-cluster
spec:
  destination:
    namespace: stage
    name: external-cluster
  project: default
  source:
  # It's possible to override helm values through different ways such as "valueFiles", "values", "valuesObject" and "parameters". 
  # Values injections have the following order of precedence parameters > valuesObject > values > valueFiles > helm repository values.yaml Or rather
    helm:
      releaseName: saba-application-from-helm-ext-clstr
      valueFiles:
        - custom-values.yaml
      values: |
        replicaCount: 8
      valuesObject:
        replicaCount: 5
      parameters:
        - name: "replicaCount"
          value: "4"
    path: v03-argocd-applications/helm/nginx
    #    repoURL: https://github.com/devopshobbies/argocd-tutorial.git
    repoURL: https://github.com/saeed-didar/argocd-tutorial.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

