apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-directory-external-cluster
spec:
  destination:
    namespace: production
    server: external-cluster
  project: default
  source:
    directory:
            #exclude: 'service.yml'
            # include: '{serviceaccount.yml,service.yml}'
      recurse: true
    path: v03-argocd-applications/directoryOfmanifests
    repoURL: https://github.com/saeed-didar/argocd-tutorial.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

